apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marquito.fullname" . }}
  labels:
    {{- include "marquito.labels" . | nindent 4 }}
data:
  MARQUITO_DB_HOST: {{ include "marquito.dbHost" . | quote }}
  MARQUITO_DB_PORT: {{ .Values.db.port | toString | quote }}
  MARQUITO_DB_NAME: {{ .Values.db.name | quote }}
  MARQUITO_DB_USER: {{ .Values.db.user | quote }}
