{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marquito.fullname" . }}-db
  labels:
    {{- include "marquito.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARQUITO_DB_PASSWORD: {{ .Values.db.password | quote }}
{{- end }}
